### ISSUE TITLE
What's the point of http://railseventstore.org/docs/changelog/ ?

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/railseventstore.org#11]
Did it use to be list of releases together with changes such as we do now at https://github.com/RailsEventStore/rails_event_store/releases ?

If so, why does it say `No changes in documentation.` instead of `No changes in API` ?

**Comment by mpraglowski** [comment]
In current form there is no point of keeping it. :+1: for remove from me. 

The idea was to have changelog of what have been added / changed in documentation but probably we might skip it. Better focus to have docs up to date and not on the changelog :)

**Comment by pawelpacana** [comment]
Agreed, removing.
