### ISSUE TITLE
Please document use of InMemoryRepository

### ISSUE THREAD

**Issue by replaid** [RailsEventStore/railseventstore.org#15]
http://railseventstore.org/docs/repository/

Please document InMemoryRepository here:

* That it exists
* What it's good for and not
* Do I need to create a new store object for tests that use it?
* Or is it best to use `RailsEventStore.event_repository =` in an RSpec `around` block to set the repo to InMemoryRepository and then replace it with the old one?

**Comment by pawelpacana** [comment]
This issue was moved to RailsEventStore/rails_event_store#240
