### ISSUE TITLE
English corrections?

### ISSUE THREAD

**Issue by joshukraine** [RailsEventStore/railseventstore.org#7]
We've been using Rails Event Store in a project, and we just recently upgraded from version 0.4.1 to 0.18.1. During the upgrade process, I spent a lot of time reading through the docs on railseventstore.org, and I found quite a few grammatical errors. I'm a native English speaker, and I would love to contribute by submitting corrections to the docs. Is that something that would be useful to you? If so let me know and I'll work on a PR.

And thanks for providing Rails Event Store as open source. Really like it!

**Comment by paneq** [comment]
@joshukraine Sure! Have a look here: https://github.com/RailsEventStore/railseventstore.org/tree/master/source/docs

Thank you very much!

**Comment by joshukraine** [comment]
OK I'll work on a PR and hopefully send it your way soon. :)
